apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - watcher-prometheusrule.yaml
  - watcher-service-monitor.yaml
  - watcher-pvc-nfs.yaml
  - watcher-pvc.yaml
  - watcher-deployment.yaml
  - watcher-rbac.yaml
  - alertmanagerconfig.yaml
  - grafana-dashboard-configmap.yaml
  - prometheusrule.yaml
  - rollout.yaml
  - service.yaml
  - servicemonitor.yaml
  - analysis.yaml
