apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: demo-app-rollout-alerts
  namespace: monitoring
  labels:
    release: prometheus-stack
    ssentinel.io/generated-by: config-compiler
    ssentinel.io/env: dev
  annotations:
    ssentinel.io/generated-by: config-compiler
    ssentinel.io/env: dev
    ssentinel.io/renderer-ref: prometheus-rule-v1
    ssentinel.io/output-kind: PrometheusRule
    ssentinel.io/compiler-profile: demo-app-compiler-profile
spec:
  groups:
  - name: demo-app-rollout.rules
    rules:
    - alert: DemoAppCanaryErrorRateSLOViolation
      expr: |-
        (
          (
            sum by (version) (
              rate(demo_http_requests_total{namespace="slo-rollout",status=~"5.."}[1m])
            )
            /
            clamp_min(
              sum by (version) (
                rate(demo_http_requests_total{namespace="slo-rollout"}[1m])
              ),
              0.001
            )
          ) * 100 > 5
        )
        and on(version)
        (
          sum by (version) (
            increase(demo_http_requests_total{namespace="slo-rollout"}[1m])
          ) >= 20
        )
      for: 30s
      labels:
        severity: critical
        project: slo-rollout-demo
        component: demo-app
        alert_type: rollout-slo
        ssentinel.io/generated-by: config-compiler
        ssentinel.io/env: dev
      annotations:
        summary: demo-app canary error rate is too high
        description: version={{ $labels.version }} 5xx error rate is above 5%.
        runbook: kubectl describe rollout demo-app -n slo-rollout
    - alert: DemoAppCanaryP95LatencySLOViolation
      expr: |-
        (
          histogram_quantile(
            0.95,
            sum by (version, le) (
              rate(demo_http_request_duration_seconds_bucket{namespace="slo-rollout"}[1m])
            )
          ) > 0.5
        )
        and on(version)
        (
          sum by (version) (
            increase(demo_http_requests_total{namespace="slo-rollout"}[1m])
          ) >= 20
        )
      for: 30s
      labels:
        severity: critical
        project: slo-rollout-demo
        component: demo-app
        alert_type: rollout-slo
        ssentinel.io/generated-by: config-compiler
        ssentinel.io/env: dev
      annotations:
        summary: demo-app canary p95 latency is too high
        description: version={{ $labels.version }} p95 latency is above 0.5s.
        runbook: kubectl describe rollout demo-app -n slo-rollout
