apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
  namespace: slo-rollout
  labels:
    app: demo-app
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
        version: v40-actions
    spec:
      containers:
      - name: demo-app
        image: 192.168.30.11:30500/sre/demo-app:v40-actions
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: VERSION
          value: "v40"
        - name: RELEASE_TAG
          value: "v40-actions"
        - name: FAULT_RATE
          value: "0"
        - name: LATENCY_MS
          value: "0"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - analysis:
          templates:
          - templateName: demo-app-error-rate
      - setWeight: 50
      - pause:
          duration: 30s
      - analysis:
          templates:
          - templateName: demo-app-error-rate
      - setWeight: 100
