apiVersion: v1
kind: Service
metadata:
  name: release-rollout-watcher
  namespace: slo-rollout
  labels:
    app.kubernetes.io/name: release-rollout-watcher
    project: slo-rollout-demo
spec:
  selector:
    app.kubernetes.io/name: release-rollout-watcher
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-rollout-watcher
  namespace: slo-rollout
  labels:
    app.kubernetes.io/name: release-rollout-watcher
    project: slo-rollout-demo
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - slo-rollout
  selector:
    matchLabels:
      app.kubernetes.io/name: release-rollout-watcher
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
